spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party
  alicloud:
    access-key: LTAI4GAPjeg7cCquVTN8fxw7
    secret-key: J85zLM8uM4Kdm9nUblECD1FDbz5nAR
    oss:
      endpoint: oss-cn-guangzhou.aliyuncs.com
      bucket: gulimall-hhello
server:
  port: 30000